name: Auto publish updated npm packages
on:
  push:
  pull_request:
    branches:
      -main

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - name: Testing 
        run: echo 'Hello world'