name: Auto publish updated npm packages
on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  publish:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    name: Auto publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Context
        run: echo "${{ (toJson(github.event.pull_request.merged)) }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          
      - name: Install dependencies
        run: npm install

      - name: Release latest package
        run: npm run semantic-release
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
    
    
    
    
